Final_year_project/Final_year_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('doctor/', include(('doctor.urls', 'doctor'), namespace='doctor')),
    path('patient/', include(('Management_system.urls', 'Management_system'), namespace='patient')),
    
    # path('social-auth/', include('social_django.urls', namespace='social')),
   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Final_year_project/Management_system/urls.py
from django.urls import path
from . import views
app_name = "Management_system"
urlpatterns = [
 path('patientdashboard/', views.Patient_dashboard, name='patientdashboard'),
 path('doctor-list/', views.doctor_list, name='doctor-list'),
 path('doctor-profile/', views.doctor_profile, name='doctor-profile'),
 path('appointment/', views.appointment, name='appointment'),
 path('appointment-form/', views.appointment_form, name='appointment-form'),
 path('patient-settings/', views.patient_settings, name='patient-settings'),
]

Final_year_project/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "accounts"
urlpatterns = [
 path('', views.check_form, name='check'),
 path('login', views.login, name='login'),
 path('logout/', views.logout, name='logout'),
 path('register/', views.register, name='register'),
 path('doctor-register/', views.doctor_register, name='doctor-register'),
 path('forget-password/', views.forget_password, name='forget-password'),
  path('google/', views.google, name='google'),

# path('password_rest/',auth_views.PasswordResetView.as_view(), name='password_reset'),
# path('password_rest/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
# path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
# path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]

Final_year_project/doctor/urls.py
from django.urls import path
from . import views
app_name = "doctor"
urlpatterns = [
 path('doctor-dashboard/', views.doctor_dashboard, name='doctor-dashboard'),
 path('all-patients/', views.all_patients, name='all-patients'),
 path('new-appointment/', views.new_appointment, name='new-appointment'),
 path('create-invoice/', views.create_invoice, name='create-invoice'),
 path('billing-list/', views.billing, name='billing-list'),
 path('doctor-settings/', views.doctor_settings, name='doctor-settings'),
]

Final_year_project/Management_system/models.py
from django.db import models
from django.contrib.auth.models import User


departments=[('Cardiologist','Cardiologist'),
('Dermatologists','Dermatologists'),
('Emergency Medicine Specialists','Emergency Medicine Specialists'),
('Allergists/Immunologists','Allergists/Immunologists'),
('Anesthesiologists','Anesthesiologists'),
('Colon and Rectal Surgeons','Colon and Rectal Surgeons')
]

venue = [('Itahari','Cardiologist'),
('Dermatologists','Dermatologists'),
('Emergency Medicine Specialists','Emergency Medicine Specialists'),
('Allergists/Immunologists','Allergists/Immunologists'),
('Anesthesiologists','Anesthesiologists'),
('Colon and Rectal Surgeons','Colon and Rectal Surgeons')
]

class Patient(models.Model):
    firts_Name = models.CharField(max_length=200)
    last_Name = models.CharField(max_length=200)
    email = models.EmailField()
    register = models.DateTimeField(auto_now_add=True)
    profile_pic= models.ImageField(upload_to='profile_pic/PatientProfilePic/',null=True,blank=True)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20,null=False)
    status=models.BooleanField(default=False)


class Doctor(models.Model):
    first_Name = models.CharField(max_length=200)
    last_Name = models.CharField(max_length=200)
    email = models.EmailField()
    register = models.DateTimeField(auto_now_add=True)
    profile_pic= models.ImageField(upload_to='profile_pic/DoctorProfilePic/',null=True,blank=True)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20,null=True)
    department= models.CharField(max_length=50,choices=departments,default='Cardiologist')
    status=models.BooleanField(default=False)
    description = models.TextField(blank=True)

    
class Appointment(models.Model):
    progress_state = [("Pending", "Pending"), ("In Progress", "In Progress"),
                      ("Waiting for receiver", "Waiting for receiver"), ("Delivered", "Delivered")]
    
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=100, unique=True)
    address = models.CharField(max_length=50, default='Itahari')
    phone_number = models.IntegerField()
    sex = models.CharField(max_length=200)
    appointment_date = models.DateField(default='2000-01-01')
    appointment_time = models.TimeField(auto_now=False, auto_now_add=False)
    progress = models.CharField(max_length=50, choices=progress_state, default='Pending')
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='appointment_patient')
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='appointment_doctor')

class History(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patient_diseases')
    diseae_name = models.CharField(max_length=40)
    medicine = models.CharField(max_length=40)
    last_checkup =  models.DateTimeField(auto_now_add=True)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='doctor_checkup')

Final_year_project/Management_system/forms.py
# import forms
# class PatientAppointmentForm(forms.ModelForm):      #used to register an appointment by patient
#     doctor = forms.TypedChoiceField(label='')   #doctor is chosed from existing doctors in hospital database
#     doctor.widget.attrs.update({'class' : 'app-form-control'})
#     #doctorId=forms.CharField(widget=forms.Select(choices=c))  
#     calldate = forms.DateField(label='',widget=SelectDateWidget(years=range(2021,2024)))    #date of appointment
#     calldate.widget.attrs.update({'class' : 'app-form-control-date'})
#     calltime = forms.TypedChoiceField(label='') #time of appointment
#     calltime.widget.attrs.update({'class' : 'app-form-control'})
#     description = forms.CharField(max_length=300,label='',widget=forms.TextInput(attrs={'placeholder': 'Description'}))
#     description.widget.attrs.update({'class' : 'app-form-control'}) 
#     def __init__(self, *args, **kwargs):
#         super(PatientAppointmentForm, self).__init__(*args, **kwargs)
#         self.fields['doctor'].choices = [(c.id, c.firstname+"("+c.department+")") for c in Doctor.objects.filter(status=True).all()]#list of doctors to choose from, taken fresh from database
#         self.fields['calltime'].choices = [('9:00 AM','9:00 AM'),('9:15 AM','9:15 AM'),('9:30 AM','9:30 AM'),('9:45 AM','9:45 AM'),('10:00 AM','10:00 AM'),('10:15 AM','10:15 AM'),('10:30 AM','10:30 AM'),('10:45 AM','10:45 AM'),('11:00 AM','11:00 AM'),('11:15 AM','11:15 AM'),('11:30 AM','11:30 AM'),('11:45 AM','11:45 AM'),('12:00 PM','12:00 PM'),('12:P5 PM','12:15 PM'),('12:30 PM','12:30 PM'),('12:45 PM','12:45 PM'),
#                                             ('14:00 PM','14:00 PM'),('14:15 PM','14:15 PM'),('14:30 PM','14:30 PM'),('14:45 PM','14:45 PM'),('15:00 PM','15:00 PM'),('15:15 PM','15:15 PM'),('15:30 PM','15:30 PM'),('15:45 PM','15:45 PM'),('16:00 PM','16:00 PM'),('16:15 PM','16:15 PM'),('16:30 PM','16:30 PM'),('16:45 PM','16:45 PM'),('17:00 PM','17:00 PM')]
#                                             #choices for time slot for appointment
#     class Meta:
#         model=Appointment
#         fields=['description','calldate','calltime']

Final_year_project/Management_system/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import  messages
from django.contrib.auth import authenticate, login
from .models import Doctor


def Patient_dashboard(request):
    return render(request, 'patientdashboard.html')

def doctor_list(request):
    doctor = Doctor.objects.all()
    context = {'doctor': doctor}
    return render(request, 'doctor-list.html', context)

def doctor_profile(request, id):
    doctor = Doctor.objects.all()
    doctor_profile = Doctor.objects.filter(doctor_id=id)
    context = {'doctor': doctor, 'doctor_profile': doctor_profile}

    return render(request, 'doctor-profile.html', context)

def appointment(request):
    return render(request, 'appointment.html')

def appointment_form(request):
    return render(request, 'appointment-form.html')

def patient_settings(request):
    return render(request, 'patient-settings.html')

# def appointment_form(request):
#     if check_admin(request.user):
#         if request.method=="POST":  #if form is submitted
#             appointmentForm = AdminAppointmentForm(request.POST)
#             if appointmentForm.is_valid():
#                 docid=appointmentForm.cleaned_data.get('doctor')    #get doctor id
#                 patid=appointmentForm.cleaned_data.get('patient')   #get patient id
#                 doc = Doctor.objects.all().filter(id=docid).first() #get doctor
#                 pat = Patient.objects.all().filter(id=patid).first()#get patient
#                 if check_avail(doc,appointmentForm.cleaned_data.get('calldate'),appointmentForm.cleaned_data.get('calltime')):  #check if appointment is available during that slot
#                     app = Appointment(patient=pat,doctor=doc,
#                                     description=appointmentForm.cleaned_data.get('description'),
#                                     calldate=appointmentForm.cleaned_data.get('calldate'),
#                                     calltime=appointmentForm.cleaned_data.get('calltime'),
#                                     status=True)    #create new appointment
#                     app.save()
#                     return redirect('bookapp_adm.html')
#                 else:   #if slot is not available, display error
#                     appointmentForm.add_error('calltime', 'Slot Unavailable.')
#                     return render(request,'hospital/Admin/bookapp_adm.html',{'appointmentForm': appointmentForm})
#             else:
#                 print(appointmentForm.errors)
#         else:
#             appointmentForm = AdminAppointmentForm()
#         return render(request,'hospital/Admin/bookapp_adm.html',{'appointmentForm': appointmentForm})
#     else:
#         auth.logout(request)
#         return redirect('login_adm.html')

Final_year_project/Management_system/templates/Add-medical.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}




{% endblock %}

Final_year_project/Management_system/templates/Base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Grace Patient Management System{% endblock %}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" href="assets/images/favicon-32x32.png">
    <!-- Base Styling  -->
    <link href="{% static 'main/css/fonts.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div id="main-wrapper" class="show">


        <!-- start logo components -->
        <div class="nav-header">
            <div class="brand-logo">
                <a href="index.html"> <img class="logo-tabib" src="{% static 'images/download.png' %}" alt=""></a>
                <a href="index.html"><img class="brand-title" src="{% static 'images/Grace1.png' %}" alt=""></a>
            </div>
        </div>
        <!-- End logo components -->


        <!-- start section sidebar -->
        <aside class="left-panel nicescroll-box">
            <nav class="navigation">
                <ul class="list-unstyled main-menu">
                    <li class="has-submenu">
                        <a href="{% url 'Management_system:patientdashboard' %}">
                            <i class="fas fa-th-large"></i>
                            <span class="nav-label">Dashboard</span>
                        </a>
                    </li>
                    <li class="has-submenu">
                        <a href="#" class="has-arrow mm-collapsed">
                            <i class="fas fa-user-md"></i>
                            <span class="nav-label">Doctors</span>
                        </a>
                        <ul class="list-unstyled mm-collapse">
                            <li><a href="{% url 'Management_system:doctor-list' %}">All Doctors</a></li>
                        </ul>
                    </li>
                    <li class="has-submenu">
                        <a href="{% url 'Management_system:appointment' %}">
                            <i class="fas fa-calendar-plus"></i>
                            <span class="nav-label">Appointment</span>
                        </a>
                    </li>
                    <li class="has-submenu">
                        <a href="#" class="has-arrow mm-collapsed">
                            <i class="fas fa-chart-pie"></i>
                            <span class="nav-label">History</span>
                        </a>
                        <ul class="list-unstyled mm-collapse">
                            <li><a href="{% url 'Management_system:doctor-list' %}">Add medical history</a></li>
                        </ul>
                        <ul class="list-unstyled mm-collapse">
                            <li><a href="{% url 'Management_system:doctor-list' %}">View medical history</a></li>
                        </ul>
                    </li>
                    <li class="has-submenu">
                        <a href="#" class="has-arrow mm-collapsed">
                            <i class="fas fa-cog"></i>
                            <span class="nav-label">Settings</span>
                        </a>
                        <ul class="list-unstyled mm-collapse">
                            <li><a href="{% url 'Management_system:patient-settings' %}">Patient Settings</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </aside>
        <!-- End section sidebar -->


        <!-- start section header -->
        <div class="header">
            <header class="top-head container-fluid">
                <div class="nav-control">
                    <div class="hamburger">
                        <span class="line"></span><span class="line"></span><span class="line"></span>
                    </div>
                </div>
                <div class="header-right">
                    <div class="fullscreen notification_dropdown">
                        <div class="full">
                            <a class="text-dark" href="#!" onclick="javascript:toggleFullScreen()">
                                <i class="fas fa-expand"></i>
                            </a>
                        </div>
                    </div>
                    <div class="my-account-wrapper">
                        <div class="account-wrapper">
                            <div class="account-control">
                                <a class="login header-profile" href="#" title="Sign in">
                                    <div class="header-info">
                                        {% if request.user.is_authenticated %}
                                        <span>{{request.user.first_name}}</span>
                                        {% endif %}
                                    </div>
                                    <img src="{% static 'images/patient1.png' %}" alt="people">
                                </a>
                                <div class="account-dropdown-form dropdown-container">
                                    <div class="form-content">
                                        <a href="{% url 'Management_system:patient-settings' %}">
                                            <i class="far fa-user"></i>
                                            <span class="ml-2">Profile</span>
                                        </a>
                                        <a href="{% url 'accounts:logout' %}">
                                            <i class="fas fa-sign-in-alt"></i>
                                            <span class="ml-2">Logout </span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
        </div>
        <!-- End section header -->

        
        {% block content %}
        {% endblock %}

<div class="footer">
    <div class="copyright">
        <p class="mb-0">Copyright © Designed &amp; Developed by <a href="uxign.com" target="_blank">Grace Patient Management</a> 2021
        </p>
    </div>
</div>
</div>


<!-- JQuery v3.5.1 -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

<!-- popper js -->
<script src="{% static 'plugins/popper/popper.min.js' %}"></script>

<!-- Bootstrap -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Moment -->
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>

<!-- Date Range Picker -->
<script src="{% static 'plugins/daterangepicker/daterangepicker.min.js' %}"></script>
{% comment %} <script src="{% static 'plugins/dateTime.min.js' %}"></script> {% endcomment %}
<!-- Datatable -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/init-tdatatable.js' %}"></script>

<!-- Chart js -->
<script src="{% static 'plugins/chart/chart/Chart.min.js' %}"></script>
{% comment %} <script src="{% static 'js/charts-custom.js' %}"></script> {% endcomment %}

<!-- Main Custom JQuery -->
<script src="{% static 'js/toggleFullScreen.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script>
    $(document).ready(function(){
    
        $('input[name="date_requested"]').daterangepicker();
    
    });
</script>
</body>
</html>

Final_year_project/Management_system/templates/appointment-form.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}

<div class="content-body">
    <div class="warper container-fluid">
        <div class="doctorino_settings main_container">
            <div class="row page-titles mx-0">
                <div class="col-sm-6 p-md-0">
                </div>
                <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card shadow mb-4">
                        <div class="card-header">
                            <h4 class="card-title">Appointment </h4>
                        </div>
                        <div class="card-body">
                            <form>
                                <div class="row">
                                    <div class="col-xl-6">
                                        <div class="form-group row">
                                            <label class="col-lg-4 col-form-label">Name
                                                <span class="text-danger">*</span>
                                            </label>
                                            <div class="col-lg-6">
                                                <input type="text" class="form-control" placeholder="Niraj">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xl-6">
                                        <div class="form-group row">
                                            <label class="col-lg-4 col-form-label">Email<span
                                                    class="text-danger">*</span></label>
                                            <div class="col-lg-6">
                                                <input type="Email" class="form-control" placeholder="nirazgajurel@gmail.com">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xl-6">
                                        <div class="form-group row">
                                            <label class="col-lg-4 col-form-label">Address <span
                                                    class="text-danger">*</span></label>
                                            <div class="col-lg-6">
                                                <input type="text" class="form-control" placeholder="Dharan">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xl-6">
                                        <div class="form-group row">
                                            <label class="col-lg-4 col-form-label">Phone<span
                                                    class="text-danger">*</span></label>
                                            <div class="col-lg-6">
                                                <input type="text" class="form-control" placeholder="212658543469">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xl-6">
                                        <div class="form-group row">
                                            <label class="col-lg-4 col-form-label">Sex</label>
                                            <div class="col-lg-6">
                                                <select class="form-control form-select">
                                                    <option>Male</option>
                                                    <option>Female</option>
                                                    <option>Others</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-xl-6">
                                        <div class="form-group row">
                                            <label class="col-lg-4 col-form-label">Date</label>
                                            <div class="col-lg-6">
                                                <input type="text" class="form-control datepicker" name="date_requested" >
                                            </div>
                                        </div>
                                    
                                    </div>
                                    <div class="col-xl-6">
                                        <div class="form-group row">
                                            <label class="col-lg-4 col-form-label">Time</label>
                                            <div class="col-lg-6">
                                                <select class="form-control form-select">
                                                    <option>9:00 AM</option>
                                                    <option>9:15 AM</option>
                                                    <option>9:30 AM</option>
                                                    <option>9:45 AM</option>
                                                    <option>10:00 AM</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>

                                    <hr>
                                    <hr>
                                    <h3>Payment Method</h3>
                                    <hr>
                                    <div class="clearfix">
                                        <input id="formcheckoutRadio4" value="" name="radio2" type="radio" class="radio" checked="checked">
                                        <label for="formcheckoutRadio4">Khalti</label>
                                    </div>
                                    <div class="clearfix">
                                        <input id="formcheckoutRadio5" value="" name="radio2" type="radio" class="radio">
                                        <label for="formcheckoutRadio5">esewa</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-11">
                                        <div class="form-group"><button type="submit" class="btn btn-primary float-end">Book Appointment</button></div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End section content -->

{% endblock %}        

Final_year_project/Management_system/templates/doctor-list.html
{% extends 'Base.html' %}
{% load static %}
{% block content %}
        <div class="content-body">
            <div class="warper container-fluid">
                <div class="all-patients main_container">
                    <div class="row page-titles mx-0">
                        <div class="col-sm-6 p-md-0">
                            <div class="welcome-text">
                                <h4 class="text-primary">Doctors List</h4>
                            </div>
                        </div>
                        <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="patientdashboard.html">Home</a></li>
                                <li class="breadcrumb-item active"><a href="/doctor-list.html">Doctors List</a></li>
                            </ol>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="widget-media list-doctors best-doctor">
                                <div class="timeline row">
                                    {% for doc in doctor%}
                                    <div class="col-sm-6 col-lg-4">
                                        <div class="timeline-panel card p-4 mb-4">
                                            <div class="media">
                                                <img src="{% if doc.profile_pic %}{{ doc.profile_pic.url }}{% else %}{% static 'images/no_image.png' %}{% endif %}">
                                            </div>
                                            <div class="media-body">
                                                <a href="#">
                                                    <h4 class="mb-2">{{doc.first_Name}}</h4>
                                                </a>
                                                <p class="mb-2">{{doc.department}}</p>
                                                <div class="star-review">
                                                    <i class="fa fa-star text-orange"></i>
                                                    <i class="fa fa-star text-orange"></i>
                                                    <i class="fa fa-star text-orange"></i>
                                                    <i class="fa fa-star text-gray"></i>
                                                    <i class="fa fa-star text-gray"></i>
                                                </div>
                                            </div>
                                            <div class="btn-group-style-1">
                                                <div class="btn-content">
                                                    <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        <i class="fas fa-ellipsis-v"></i>
                                                    </button>
                                                    <div class="dropdown-menu">
                                                        <div class="form-content">
                                                            <a href="{%url 'doctor-profile'%}">
                                                                <span class="ml-2">View Profile</span>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>   
{% endblock %}