Final_year_project/Final_year_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('doctor/', include(('doctor.urls', 'doctor'), namespace='doctor')),
    path('patient/', include(('Management_system.urls', 'Management_system'), namespace='patient')),
    
    # path('social-auth/', include('social_django.urls', namespace='social')),
   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Final_year_project/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "accounts"
urlpatterns = [
 path('', views.check_form, name='check'),
 path('login', views.login, name='login'),
 path('logout/', views.logout, name='logout'),
 path('register/', views.register, name='register'),
 path('doctor-register/', views.doctor_register, name='doctor-register'),
 path('forget-password/', views.forget_password, name='forget-password'),
  path('google/', views.google, name='google'),

# path('password_rest/',auth_views.PasswordResetView.as_view(), name='password_reset'),
# path('password_rest/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
# path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
# path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]

Final_year_project/doctor/urls.py
from django.urls import path
from . import views
app_name = "doctor"
urlpatterns = [
 path('doctor-dashboard/', views.doctor_dashboard, name='doctor-dashboard'),
 path('all-patients/', views.all_patients, name='all-patients'),
 path('new-appointment/', views.new_appointment, name='new-appointment'),
 path('create-invoice/', views.create_invoice, name='create-invoice'),
 path('billing-list/', views.billing, name='billing-list'),
 path('doctor-settings/', views.doctor_settings, name='doctor-settings'),
]

Final_year_project/accounts/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password):
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have a username')
        
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )
        user.is_active = True
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_doctor(self, first_name, last_name, username, email, password, license):
        if len(license)!= 8:
            raise ValueError('Doctor must have a license valid number')

        user = self.create_doctor(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
            license = license,
            password = password,
        )

        user.is_doctor= True
        user.is_active=True
        user.save(using=self._db)
        return user


    def create_superuser(self, first_name, last_name, email, username, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name,
        )

        user.is_superuser= True
        user.is_active=True
        user.is_staff=True
        user.is_admin=True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    username = models.CharField(max_length=30, unique=True)
    email = models.EmailField(max_length=100, unique=True)

    # required 
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = MyAccountManager()

    def __str__(self):
        return self.email
    

    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_label):
        return True

# class Doctor(AbstractBaseUser, PermissionsMixin):
#     first_name = models.CharField(max_length=30)
#     last_name = models.CharField(max_length=30)
#     username = models.CharField(max_length=30, unique=True)
#     email = models.EmailField(max_length=100, unique=True)
#     license_number = models.CharField(max_length=100, unique=True)

#     # required 
#     date_joined = models.DateTimeField(auto_now_add=True)
#     last_login = models.DateTimeField(auto_now=True)
#     is_active = models.BooleanField(default=False)
#     is_admin = models.BooleanField(default=False)
#     is_staff = models.BooleanField(default=False)
#     is_superuser = models.BooleanField(default=False)

#     USERNAME_FIELD = 'email'
#     REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

#     objects = MyAccountManager()

#     def __str__(self):
#         return self.email
    

#     def has_perm(self, perm, obj=None):
#         return self.is_admin
    
#     def has_module_perms(self, app_label):
#         return True

Final_year_project/accounts/forms.py
from email.policy import default
from django import forms
from .models import Account

class RegistrationForm(forms.ModelForm):
  
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password',
    }), min_length=8)
    confirm_password = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Confirm Password',
    }))
    term = forms.BooleanField(required=True)

    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'email', 'password')
    def clean_data(self):
        cleaned_data = super(RegistrationForm, self).clean_data()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError(
                'Password did not match'
            )
        email = self.cleaned_data.get('email')
        try:
            Account.objects.get(email=email)
            raise forms.ValidationError(
                'Email already exists'
            )
        except Account.DoesNotExist:
            pass
        
    def __init__(self, *args, **kargs):
        super(RegistrationForm, self).__init__(*args, **kargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'First name'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Last name'})
        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder': 'example@domain.com'})
        self.fields['term'].widget.attrs.update({'id': 'term_cond'})

class DoctorRegistrationForm(forms.ModelForm):
  
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password',
    }), min_length=8)
    confirm_password = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Confirm Password',
    }))
    license_number = forms.CharField(label='license number', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'license number',
    }))
    term = forms.BooleanField(required=True)

    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'email', 'password', 'license_number')
    def clean(self):
        cleaned_data = super(DoctorRegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError(
                'Password did not match'
            )
        email = self.cleaned_data.get('email')
        try:
            Account.objects.get(email=email)
            raise forms.ValidationError(
                'Email already exists'
            )
        except Account.DoesNotExist:
            pass
        
    def __init__(self, *args, **kargs):
        super(DoctorRegistrationForm, self).__init__(*args, **kargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'First name'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Last name'})
        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder': 'example@domain.com'})
        self.fields['license_number'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Np0865743255'})
        self.fields['term'].widget.attrs.update({'id': 'term_cond'})

# class LoginForm(forms.Form):
#     email = forms.EmailField()
#     password = forms.CharField(widget= forms.PasswordInput)
#     remember_password = forms.BooleanField()
    
#     def __init__(self, *args, **kargs):
#         super(RegistrationForm, self).__init__(*args, **kargs)
#         self.fields['password'].widget.attrs.update({'class': 'form-control', 'placeholder': 'password'})
#         self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder': 'example@domain.com'})
#         self.fields['remember_password'].widget.attrs.update({'id': 'remember_password'})

Final_year_project/accounts/views.py
from django.shortcuts import render, HttpResponse
from django.shortcuts import render, redirect
from .forms import RegistrationForm, DoctorRegistrationForm
from .models import Account
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.views import password_reset, password_reset_confirm
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            username = first_name + " " + last_name 
            user = Account.objects.create_user(first_name=first_name, last_name=last_name, email=email, username=username, password=password)
            user.save()
            return render(request, 'Login.html')

    else:
        form = RegistrationForm()
    context = {
        'form': form,
    }
    return render(request, 'patient-register.html', context)


def doctor_register(request):
    if request.method == 'POST':
        form = DoctorRegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            username = first_name + " " + last_name 
            license = form.cleaned_data['license']
            user = Account.objects.create_doctor(first_name=first_name, last_name=last_name, email=email, username=username, password=password, license=license)
            user.save()
            return render(request, 'Login.html')

    else:
        form = DoctorRegistrationForm()
    context = {
        'form': form,
    }
    return render(request, 'doctor-register.html', context)

def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        license = ""
        # license = request.POST['license']
        user = auth.authenticate(email=email, password=password)
        request.session['email'] = email
        if len(license) == 8:
            request.session['license'] = license
        if user is not None:
            auth.login(request, user)
            if len(license)==8:
                return redirect('doctor:doctor-dashboard')
            return redirect('Management_system:patientdashboard')
        else:
            messages.error(request, 'Invalid email or password')
            return render(request, 'Login.html')

    return render(request, 'Login.html')

def check_form(request):
    if request.session.has_key("license") and request.session.has_key("email"): 
        return redirect('doctor:doctor-dashboard')
    elif request.session.has_key("email"): 
        return redirect('Management_system:patientdashboard')
    else:
        return redirect('accounts:login')

@login_required(login_url= 'login')
def logout(request):
    try:
        if request.session.has_key("license"):
            del request.session['license'] 
        del request.session['email']
    except:
      pass
    return redirect('accounts:login')

def doctor_register(request):
   return render(request, 'doctor-register.html')


def forget_password(request):
    return render(request, 'forget-password.html')

def google(request):
    print(type(request.session))
    return HttpResponse("googlre hu meh")

Final_year_project/accounts/templates/Login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Grace Patient Management System{% endblock %}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" href="assets/images/favicon-32x32.png">
    <!-- Base Styling  -->
    <link href="{% static 'main/css/fonts.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
    <style>
        #licence-div {
            display: none;
        }
        
        #licence-div.show {
            display: block;
        }
    </style>
    
</head>
{% block content %}
<body>
    <div id="main-wrapper" class="show">

        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-7 p-0 b-center bg-size">
                    <img class="img-fluid" src= "{%static 'images/bg-register.jpg' %}" alt="Grace app">
                </div>
                <div class="col-xl-5 p-0">
                    <div class="login-tabib">
                        <div>
                            <div class="text-center">
                                <a class="logo" href="index.html">
                                    <img class="img-fluid" src= "{% static 'images/Grace1.png' %}" alt="loogin page">
                                </a>
                            </div>
                            <div class="login-main">
                                <form class="theme-form" action="{% url 'accounts:login' %}" method="POST">
                                    {% csrf_token %}
                                    <h4>Sign in to account</h4>
                                    <p>Enter your email & password to login </p>
                                    <div class="form-group m-b-10">
                                        <label class="col-form-label">Email Address</label>
                                         <input class="form-control" type="email" name="email" placeholder="nirazgajurel21@gmail.com">
                                    </div>
                                    <div class="form-group m-b-10">
                                        <label class="col-form-label">Password</label>
                                        <div class="form-input position-relative">
                                           
                                        <input class="form-control" type="password" name="password" placeholder="*********"> 
                                            <div class="show-hide"><span class="show"></span></div>
                                        </div>
                                    </div>
                                    <div class="form-group m-b-10" id="licence-div">
                                        <label class="col-form-label">License Number</label>
                                        <div class="form-input position-relative">
                                           
                                        <input class="form-control" type="text" name="License Number" placeholder=""> 
                                            <div class="show-hide"><span class="show"></span></div>
                                        </div>
                                    </div>
                                    <div class="form-group mb-0">
                                        <div class="p-0 checkbox">
                                            <input type="checkbox" id="loginDoctor" required="">
                                            <label class="text-muted" for="loginDoctor">Login as doctor</label>
                                        </div>
                                        <a class="link text-primary" href="{% url 'accounts:forget-password' %}">Forgot password?</a>
                                        <div class="mt-3">
                                            <button type="submit" href="{% url 'accounts:login' %}" class="btn btn-primary w-100" > sign in </button>
                                        </div>                                  
                                    </div>
                                
                                    <p class="mt-4 mb-3" style="text-align: center;">Don't have account?<a class="ms-2 text-primary text-center" href="{% url 'accounts:register' %}">Create Account</a>
                                    </p>
                                    <div class="row">
                                        <div class="col-12" style="text-align: center;">
                                          <a class="btn btn-outline-dark" href="{% url 'accounts:google' %}" role="button" style="text-transform:none">
                                            <img width="20px" style="margin-bottom:1px; margin-right:10px" alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png" />
                                            Login with Google
                                          </a>
                                        </div>
                                      </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- JQuery v3.5.1 -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

    <!-- popper js -->
    <script src="{% static 'plugins/popper/popper.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>

    <!-- Moment -->
    <script src="{% static 'plugins/moment/moment.min.js' %}"></script>

    <!-- Date Range Picker -->
    <script src="{% static 'plugins/daterangepicker/daterangepicker.min.js' %}"></script>

    <!-- Main Custom JQuery -->
    <script src="{% static 'js/toggleFullScreen.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <!-- Minified CSS and JS -->
    <link   rel="stylesheet" 
     href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
     integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
     crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" 
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" 
     crossorigin="anonymous">
    </script>
    <script>
        $(document).ready(function(){
            var licence_div = document.getElementById('licence-div'); 
            $("#loginDoctor").on('click', function (e){
               if($(this).is(':checked')){
                licence_div.classList.add("show");
                }else{
                    licence_div.classList.remove("show");
                }
            });
        });
    </script>

{% endblock %}

</body>

</html>

Final_year_project/accounts/templates/forget-password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Grace Patient Management System{% endblock %}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" href="assets/images/favicon-32x32.png">
    <!-- Base Styling  -->
    <link href="{% static 'main/css/fonts.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
</head>
{% block content %}
<body>
    <div id="main-wrapper" class="show">

        <div class="login-tabib">
            <div>
                <div class="text-center">
                    <a class="logo" href="index.html">
                        <img class="img-fluid" src="{% static 'images/Grace1.png' %}" alt="loogin page">
                    </a>
                </div>
                <div class="login-main">
                    <form class="theme-form">
                        <h4>Recover my password </h4>
                        <div class="form-group m-b-10">
                            <p>Please enter your email address below to receive instructions for resetting password.</p>
                            <div class="form-input position-relative">
                                <input class="form-control" type="email" placeholder="Enter your email">
                                <div class="show-hide"><span class="show"></span></div>
                            </div>
                        </div>
                        <div class="form-group mb-0">
                            <div class="mt-3">
                                <a href="#" class="btn btn-primary w-100">Reset password</a>
                            </div>
                        </div>
                        <p class="mt-4 mb-0">Know your password?<a class="ms-2 text-primary text-center" href="{% url 'accounts:login'%}">Sign in</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>

    </div>

    <!-- JQuery v3.5.1 -->
    <script src="assets/plugins/jquery/jquery.min.js"></script>

    <!-- popper js -->
    <script src="assets/plugins/popper/popper.min.js"></script>

    <!-- Bootstrap -->
    <script src="assets/plugins/bootstrap/js/bootstrap.js"></script>

    <!-- Moment -->
    <script src="assets/plugins/moment/moment.min.js"></script>

    <!-- Date Range Picker -->
    <script src="assets/plugins/daterangepicker/daterangepicker.min.js"></script>

    <!-- Main Custom JQuery -->
    <script src="assets/js/toggleFullScreen.js"></script>
    <script src="assets/js/main.js"></script>

{% endblock %}

</body>

</html>

Final_year_project/accounts/templates/patient-register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Grace Patient Management System{% endblock %}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" href="assets/images/favicon-32x32.png">
    <!-- Base Styling  -->
    <link href="{% static 'main/css/fonts.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
</head>
{% block content %}
<body>
    <div id="main-wrapper" class="show">

        <div class="login-tabib">
            <div>
                <div class="text-center">
                    <a class="logo" href="index.html">
                        <img class="img-fluid" src="{%static 'images/Grace1.png' %}" alt="loogin page">
                    </a>
                </div>
                <div class="login-main">
                    <form class="theme-form" action="{% url 'accounts:register' %}" method="POST">
                        {% csrf_token %}
                        <h4>Create your account</h4>
                        <p>Enter your personal details to create account</p>
                        <div class="form-group m-b-10">
                            <label class="col-form-label pt-0">Your Name</label>
                            <div class="row g-2">
                                <div class="col-md-12 col-lg-6">
                                    <div class="form-group mb-0">
                                        {{form.first_name}}
                                    </div>
                                </div>
                                <div class="col-md-12 col-lg-6">
                                    <div class="form-group mb-0">
                                       {{form.last_name}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group m-b-10">
                            <label class="col-form-label">Email Address</label>
                            {{form.email}}
                        </div>
                        <div class="form-group m-b-10">
                            <label class="col-form-label">Password</label>
                            <div class="form-input position-relative">
                                {{ form.password}}
                                <div class="show-hide"><span class="show"></span></div>
                            </div>
                        </div>
                        <div class="form-group m-b-10">
                            <label class="col-form-label">Confirm Password</label>
                            <div class="form-input position-relative">
                                {{ form.confirm_password}}
                                <div class="show-hide"><span class="show"></span></div>
                            </div>
                        </div>
                        <div class="form-group mb-0">
                            <div class="checkbox p-0">
                                {{form.term}}
                             <label class="text-muted" for="term_cond">Agree with privacy policy</label>
                            </div>
                            {{ form.email.errors }}
					        {{ form.non_field_errors }}
                            <button type="submit" class="btn btn-primary w-100" > Register </button>
                        </div>
                        <p class="mt-4 mb-1">Already have an account?<a class="ms-2 text-primary" href="{% url 'accounts:login' %}">Sign in</a>
                        </p>
                        <a class="ms-1 text-primary" href="{%url 'accounts:doctor-register' %}">Register as doctor?</a>
                    

                    </form>
                </div>
            </div>
        </div>

    </div>

    <!-- JQuery v3.5.1 -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

    <!-- popper js -->
    <script src="{% static 'plugins/popper/popper.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>

    <!-- Moment -->
    <script src="{% static 'plugins/moment/moment.min.js' %}"></script>

    <!-- Main Custom JQuery -->
    <script src="{% static 'js/toggleFullScreen.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

{% endblock %}

</body>

</html>