Final_year_project/Final_year_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('doctor/', include(('doctor.urls', 'doctor'), namespace='doctor')),
    path('patient/', include(('Management_system.urls', 'Management_system'), namespace='patient')),
    
    # path('social-auth/', include('social_django.urls', namespace='social')),
   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Final_year_project/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "accounts"
urlpatterns = [
 path('', views.check_form, name='check'),
 path('login', views.login, name='login'),
 path('logout/', views.logout, name='logout'),
 path('register/', views.register, name='register'),
 path('doctor-register/', views.doctor_register, name='doctor-register'),
 path('forget-password/', views.forget_password, name='forget-password'),
  path('google/', views.google, name='google'),

# path('password_rest/',auth_views.PasswordResetView.as_view(), name='password_reset'),
# path('password_rest/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
# path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
# path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]

Final_year_project/doctor/urls.py
from django.urls import path
from . import views
app_name = "doctor"
urlpatterns = [
 path('doctor-dashboard/', views.doctor_dashboard, name='doctor-dashboard'),
 path('all-patients/', views.all_patients, name='all-patients'),
 path('new-appointment/', views.new_appointment, name='new-appointment'),
 path('create-invoice/', views.create_invoice, name='create-invoice'),
 path('billing-list/', views.billing, name='billing-list'),
 path('doctor-settings/', views.doctor_settings, name='doctor-settings'),
]

Final_year_project/doctor/models.py
from django.db import models

# Create your models here.

Final_year_project/doctor/views.py
from django.shortcuts import render

# Create your views here.
def doctor_dashboard(request):
    return render(request, 'doctor-dashboard.html')
    
def all_patients(request):
    return render(request, 'all-patients.html')

def new_appointment(request):
    return render(request, 'new-appointment.html')

def create_invoice(request):
    return render(request, 'create-invoice.html')

def billing(request):
    return render(request, 'billing-list.html')

def doctor_settings(request):
    return render(request, 'doctor-settings.html')

Final_year_project/doctor/templates/create-invoice.html
{% extends 'index.html' %}
{% load static %}
{% block content %}


        <!-- start section content -->
        <div class="content-body ">
            <div class="warper container-fluid">
                <div class="create_invoice main_container">
                    <div class="row page-titles mx-0">
                        <div class="col-sm-6 p-md-0">
                            <div class="welcome-text">
                                <h4 class="text-primary">Create-invoice</h4>
                            </div>
                        </div>
                        <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                                <li class="breadcrumb-item active"><a href="/create-invoice.html">create-invoice</a>
                                </li>
                            </ol>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card shadow mb-4">
                                <div class="card-header">
                                    <h4 class="card-title"> create invoice </h4>
                                </div>
                                <div class="card-body">
                                    <form>
                                        <div class="row">
                                            <div class="col-lg-4 col-sm-6">
                                                <div class="form-group">
                                                    <select class="form-control form-select">
                                                        <option>Select Patient...</option>
                                                        <option>TEST</option>
                                                        <option>TEST</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-sm-6">
                                                <div class="form-group">
                                                    <select class="form-control form-select">
                                                        <option>Payment Mode</option>
                                                        <option>Cash</option>
                                                        <option>Cheque</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col">
                                                <div class="form-group">
                                                    <select class="form-control form-select">
                                                        <option>Payment Status</option>
                                                        <option>Paid</option>
                                                        <option>Unpaid</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row ">
                                            <div class="col-lg-4 col-sm-6">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" placeholder="Invoice Title">
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-sm-6 ">
                                                <div class="form-group">
                                                    <div class="input-group ">
                                                        <div class="input-group-prepend">
                                                            <span class="input-group-text" id="basic-addon1">$</span>
                                                        </div>
                                                        <input type="text" class="form-control" placeholder="Amount">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col">
                                                <div class="form-group">
                                                    <button type="button" class="btn btn-primary w-100 h-56">Create
                                                        Invoice</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End section content -->
   

 {% endblock %}

Final_year_project/doctor/templates/doctor-settings.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
        <!-- start section content -->
        <div class="content-body">
            <div class="warper container-fluid">
                <div class="doctorino_settings main_container">
                    <div class="row page-titles mx-0">
                        <div class="col-sm-6 p-md-0">
                            <div class="welcome-text">
                                <h4 class="text-primary">Doctor Settings</h4>
                            </div>
                        </div>
                        <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                                <li class="breadcrumb-item active"><a href="/doctor-settings.html">Doctor Settings</a>
                                </li>
                            </ol>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card shadow mb-4">
                                <div class="card-header">
                                    <h4 class="card-title"> Doctor Settings </h4>
                                </div>
                                <div class="card-body">
                                    <form>
                                            <div class="row">
                                                <div class="col-xl-4">
                                                    <div class="form-group row widget-3">
                                                        <div class="col-lg-10">
                                                            <div class="form-input">
                                                                <label class="labeltest" for="file-ip-1">
                                                                    <span> click to upload image </span>
                                                                </label>
                                                                <input type="file" id="file-ip-1" accept="image/*" onchange="showPreview(event);">
                                                                <div class="preview">
                                                                    <img id="file-ip-1-preview" src="#" alt="img">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-xl-4">
                                                    <div class="form-group">
                                                        <input type="text" class="form-control" placeholder="Title (ex. Dr)">
                                                    </div>
                                                    <div class="form-group">
                                                        <input type="text" class="form-control" placeholder="Address">
                                                    </div>
                                                    <div class="form-group">
                                                        <input type="text" class="form-control" placeholder="Hospital Name">
                                                    </div>
                                                    <div class="form-group">
                                                        <input type="email" class="form-control" placeholder="Email">
                                                    </div>
                                                    <div class="form-group">
                                                        <input type="text" class="form-control" placeholder="Mobile No.">
                                                    </div>
                                                </div>
                                                <div class="col-xl-4">
                                                    <div class="form-group">
                                                        <div class="input-group">
                                                            <input type="text" class="form-control" placeholder="Name">
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <select class="form-control form-select">
                                                            <option> status </option>
                                                            <option>on</option>
                                                            <option>Off</option>
                                                        </select>
                                                    </div>
                                                    <div class="form-group">
                                                        <select class="form-control form-select">
                                                            <option>District</option>
                                                            <option>Morang</option>
                                                            <option>Jhapa</option>
                                                            <option>Dhankuta</option>
                                                            <option>Sunsari</option>
                                                            <option>Saptari</option>
                                                        </select>
                                                    </div>
                                                    <div class="form-group">
                                                        <select class="form-control form-select">
                                                            <option>Specialist</option>
                                                            <option>Cardiologist</option>
                                                            <option>Dermatologists</option>
                                                            <option>Colon and Rectal Surgeons</option>
                                                            <option>Anesthesiologists</option>
                                                            <option>Allergists/Immunologists</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <hr>
                                            </div>
                                        <div class="row">
                                            <label class="col-sm-4 col-md-3 col-form-label">Saturday</label>
                                            <div class="col-sm-4 col-md-4">
                                                <div class="form-group"> <input type="time" class="form-control"></div>
                                            </div>
                                            <div class="col-sm-4 col-md-4">
                                                <div class="form-group"><input type="time" class="form-control"></div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <label class="col-sm-4 col-md-3 col-form-label">Sunday</label>
                                            <div class="col-sm-4 col-md-4">
                                                <div class="form-group"><input type="time" class="form-control"></div>
                                            </div>
                                            <div class="col-sm-4 col-md-4">
                                                <div class="form-group"> <input type="time" class="form-control"></div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <label class="col-sm-4 col-md-3 col-form-label">Monday</label>
                                            <div class="col-sm-4 col-md-4">
                                                <div class="form-group"> <input type="time" value="08:00" class="form-control"></div>
                                            </div>
                                            <div class="col-sm-4 col-md-4">
                                                <div class="form-group"> <input type="time" value="17:00" class="form-control"></div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <label class="col-sm-4 col-md-3 col-form-label">Tuesday</label>
                                            <div class="col-sm-4 col-md-4">
                                                <div class="form-group"> <input type="time" value="08:00" class="form-control"></div>
                                            </div>
                                            <div class="col-sm-4 col-md-4">
                                                <div class="form-group"> <input type="time" value="17:00" class="form-control"></div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <label class="col-sm-4 col-md-3 col-form-label">Wednseday</label>
                                            <div class="col-sm-4 col-md-4">
                                                <div class="form-group">
                                                    <input type="time" value="08:00" class="form-control">
                                                </div>
                                            </div>
                                            <div class="col-sm-4 col-md-4">
                                                <div class="form-group"><input type="time" value="17:00" class="form-control"></div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <label class="col-sm-4 col-md-3 col-form-label">Thurday</label>
                                            <div class="col-sm-4 col-md-4">
                                                <div class="form-group"><input type="time" value="08:00" class="form-control"></div>
                                            </div>
                                            <div class="col-sm-4 col-md-4">
                                                <div class="form-group"> <input type="time" value="17:00" class="form-control"></div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <label class="col-sm-4 col-md-3 col-form-label">Friday</label>
                                            <div class="col-sm-4 col-md-4">
                                                <div class="form-group">
                                                    <input type="time" value="08:00" class="form-control">
                                                </div>
                                            </div>
                                            <div class="col-sm-4 col-md-4">
                                                <div class="form-group"><input type="time" value="17:00" class="form-control"></div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-11">
                                                <div class="form-group"><button type="submit" class="btn btn-primary float-end">Save</button></div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End section content -->


{% endblock %}      

Final_year_project/doctor/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Grace Patient Management System{% endblock %}</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" href="assets/images/favicon-32x32.png">
    <!-- Base Styling  -->
    <link href="{% static 'main/css/fonts.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div id="main-wrapper" class="show">


        <!-- start logo components -->
        <div class="nav-header">
            <div class="brand-logo">
                <a href="index.html"> <img class="logo-tabib" src="{% static 'images/download.png' %}" alt=""></a>
                <a href="index.html"><img class="brand-title" src="{% static 'images/Grace1.png' %}" alt=""></a>
            </div>
        </div>
        <!-- End logo components -->

        
         <!-- start section sidebar -->
         <aside class="left-panel nicescroll-box">
            <nav class="navigation">
                <ul class="list-unstyled main-menu">
                    <li class="has-submenu active">
                        <a href="{% url 'doctor:doctor-dashboard' %}">
                            <i class="fas fa-th-large"></i>
                            <span class="nav-label">Dashboard</span>
                        </a>
                    </li>
                    <li class="has-submenu">
                        <a href="#" class="has-arrow mm-collapsed">
                            <i class="fas fa-users"></i>
                            <span class="nav-label">Patients</span>
                        </a>
                        <ul class="list-unstyled mm-collapse">
                            <li><a href="{% url 'doctor:all-patients' %}">All Patients</a></li>
                        </ul>
                    </li>
                    <li class="has-submenu">
                        <a href="{% url 'doctor:new-appointment' %}">
                            <i class="fas fa-calendar-plus"></i>
                            <span class="nav-label">Appointment</span>
                        </a>
                    </li>
                    <li class="has-submenu">
                        <a href="#" class="has-arrow mm-collapsed">
                            <i class="fas fa-file-invoice"></i>
                            <span class="nav-label">Billing</span>
                        </a>
                        <ul class="list-unstyled mm-collapse">
                            <li><a href="{% url 'doctor:create-invoice'%}">Create Invoice</a></li>
                            <li><a href="{% url 'doctor:billing-list' %}">Billing List</a></li>
                        </ul>
                    </li>
                    <li class="has-submenu">
                        <a href="#" class="has-arrow mm-collapsed">
                            <i class="fas fa-cog"></i>
                            <span class="nav-label">Settings</span>
                        </a>
                        <ul class="list-unstyled mm-collapse">
                            <li><a href="{% url 'doctor:doctor-settings' %}">Doctor Settings</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </aside>
        <!-- End section sidebar -->

        <!-- start section header -->
        <div class="header">
            <header class="top-head container-fluid">
                <div class="nav-control">
                    <div class="hamburger">
                        <span class="line"></span><span class="line"></span><span class="line"></span>
                    </div>
                </div>
                <div class="header-right">
                    <div class="fullscreen notification_dropdown">
                        <div class="full">
                            <a class="text-dark" href="#!" onclick="javascript:toggleFullScreen()">
                                <i class="fas fa-expand"></i>
                            </a>
                        </div>
                    </div>
                    <div class="my-account-wrapper">
                        <div class="account-wrapper">
                            <div class="account-control">
                                <a class="login header-profile" href="#" title="Sign in">
                                    <div class="header-info">
                                        <span>Dr Roberts</span>
                                    </div>
                                    <img src="{% static 'images/client.jpg' %}" alt="people">
                                </a>
                                <div class="account-dropdown-form dropdown-container">
                                    <div class="form-content">
                                        <a href="doctor-settings.html">
                                            <i class="far fa-user"></i>
                                            <span class="ml-2">Profile</span>
                                        </a>
                                        <a href="{% url 'accounts:logout' %}">
                                            <i class="fas fa-sign-in-alt"></i>
                                            <span class="ml-2">Logout </span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
        </div>


                {% block content %}
                {% endblock %}

        <div class="footer">
            <div class="copyright">
                <p class="mb-0">Copyright © Designed &amp; Developed by <a href="uxign.com" target="_blank">Grace Patient Management</a> 2021
                </p>
            </div>
        </div>
    </div>

    
    <!-- JQuery v3.5.1 -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

    <!-- popper js -->
    <script src="{% static 'plugins/popper/popper.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>

    <!-- Moment -->
    <script src="{% static 'plugins/moment/moment.min.js' %}"></script>

    <!-- Date Range Picker -->
    <script src="{% static 'plugins/daterangepicker/daterangepicker.min.js' %}"></script>

    <!-- Datatable -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/init-tdatatable.js' %}"></script>

    <!-- Chart js -->
    <script src="{% static 'plugins/chart/chart/Chart.min.js' %}"></script>
    <script src="{% static 'js/charts-custom.js' %}"></script>

    <!-- Main Custom JQuery -->
    <script src="{% static 'js/toggleFullScreen.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>